name: Train ML Experiment
# This workflow is triggered on pull requests to any brach except master.
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
    - '**-model'
  workflow_dispatch:

env:
  TAG: 'tag'

jobs:
  experiment:
    name: execute experiment and post results
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      # docker build . \
      # --rm \
      # --file Dockerfile \
      # --tag $TAG
      run: |
        printenv
    
    - name: Run unit testing
      run: |
        echo '$GITHUB_REPOSITORY:1'
        echo 'running unittest $GITHUB_RUN_ID'

    - name: Train model and save analytics
      run: echo 'training model with id of $GITHUB_RUN_NUMBER'
        
  
  
  
  
