name: Train ML Experiment
# This workflow is triggered on pull requests to any brach except master.
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:


jobs:
  experiment:
    name: execute experiment and post results
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: Build the Docker image
      run: |
        docker build /src --rm --tag jorgeruiz97/backtestEnv:1.0

    - name: Run unit testing
      run: python src/test.py

    - name: Train model and save analytics
      run: python src/train.py

    - name: Train model and save analytics
      run: python src/backtest.py
        
    - name: Post Report to Pull-Request
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: 'Experiment results: [Train & backtest Report](https://www.google.com)'
  
  
  
